#!/usr/bin/env python3
"""Generate app/src/share/cjk-font.ts — a 16x16 bitmap font for the share renderer.

Source font: NotoSansSC-Regular.ttf (SIL OFL) bundled with the Kimi Work
managed Python runtime. Coverage: full GB2312 hanzi block (6763 chars) plus
GB2312 fullwidth punctuation/symbol rows, so arbitrary user pattern names
render instead of empty boxes. ASCII stays on the hand-drawn 5x7 pixel font
(it matches the perler-bead aesthetic).
"""
from __future__ import annotations

import base64
import io
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FONT_PATH = Path(
    r"C:/Users/11929/AppData/Roaming/kimi-desktop/daimon-share/daimon/runtime/python/fonts/NotoSansSC-Regular.ttf"
)
OUT_PATH = Path(__file__).resolve().parent.parent / "app" / "src" / "share" / "cjk-font.ts"

SIZE = 16


def gb2312_chars() -> list[str]:
    chars: list[str] = []
    seen: set[str] = set()

    def add(ch: str) -> None:
        if ch and ch not in seen and ord(ch) > 127:
            seen.add(ch)
            chars.append(ch)

    for hi in range(0xA1, 0xA4):  # punctuation / symbol / fullwidth ASCII rows
        for lo in range(0xA1, 0xFF):
            try:
                add(bytes([hi, lo]).decode("gb2312"))
            except UnicodeDecodeError:
                continue
    for hi in range(0xB0, 0xF8):  # hanzi block
        for lo in range(0xA1, 0xFF):
            try:
                ch = bytes([hi, lo]).decode("gb2312")
            except UnicodeDecodeError:
                continue
            if "一" <= ch <= "鿿":
                add(ch)
    for ch in "·×★☆♥♡～―…":  # GB2312 maps 0xA1A4 to U+30FB; add common name decorations
        add(ch)
    return chars


def render_glyph(font: ImageFont.FreeTypeFont, ch: str) -> bytes:
    img = Image.new("L", (SIZE, SIZE), 0)
    draw = ImageDraw.Draw(img)
    left, top, right, bottom = font.getbbox(ch)
    w, h = right - left, bottom - top
    x = (SIZE - w) // 2 - left
    y = (SIZE - h) // 2 - top
    draw.text((x, y), ch, font=font, fill=255)
    rows = []
    px = img.load()
    for yy in range(SIZE):
        bits = 0
        for xx in range(SIZE):
            if px[xx, yy] >= 110:
                bits |= 1 << (SIZE - 1 - xx)
        rows.append(bits)
    return b"".join(row.to_bytes(2, "big") for row in rows)


def main() -> None:
    font = ImageFont.truetype(str(FONT_PATH), 13)
    chars = gb2312_chars()
    data = b"".join(render_glyph(font, ch) for ch in chars)
    order = "".join(chars)
    payload = base64.b64encode(data).decode("ascii")

    out = io.StringIO()
    out.write("// Generated by scripts/gen-cjk-font.py from NotoSansSC-Regular.ttf (SIL OFL).\n")
    out.write("// 16x16 bitmap glyphs, 2 big-endian bytes per row, MSB = leftmost pixel.\n")
    out.write("// Coverage: GB2312 fullwidth punctuation + fullwidth ASCII + all 6763 hanzi.\n")
    out.write("// Do not edit by hand; regenerate with: python scripts/gen-cjk-font.py\n")
    out.write(f"const ORDER = {order!r}\n")
    out.write("const DATA =\n")
    for i in range(0, len(payload), 100):
        out.write(f"  {payload[i:i+100]!r} +\n")
    out.write("  ''\n\n")
    out.write(
        "function decode(data: string): Uint8Array {\n"
        "  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'\n"
        "  const table = new Map<string, number>()\n"
        "  for (let i = 0; i < 64; i++) table.set(alphabet[i], i)\n"
        "  const clean = data.replace(/=+$/, '')\n"
        "  const out = new Uint8Array(Math.floor((clean.length * 3) / 4))\n"
        "  let acc = 0\n"
        "  let bits = 0\n"
        "  let pos = 0\n"
        "  for (const ch of clean) {\n"
        "    acc = (acc << 6) | (table.get(ch) ?? 0)\n"
        "    bits += 6\n"
        "    if (bits >= 8) {\n"
        "      bits -= 8\n"
        "      out[pos++] = (acc >> bits) & 0xff\n"
        "    }\n"
        "  }\n"
        "  return out\n"
        "}\n\n"
        "function buildMap(): Map<string, Uint16Array> {\n"
        "  const bytes = decode(DATA)\n"
        "  const map = new Map<string, Uint16Array>()\n"
        "  const chars = Array.from(ORDER)\n"
        "  for (let i = 0; i < chars.length; i++) {\n"
        "    const glyph = new Uint16Array(16)\n"
        "    for (let row = 0; row < 16; row++) {\n"
        "      const off = i * 32 + row * 2\n"
        "      glyph[row] = (bytes[off] << 8) | bytes[off + 1]\n"
        "    }\n"
        "    map.set(chars[i], glyph)\n"
        "  }\n"
        "  return map\n"
        "}\n\n"
        "export const CJK_FONT: ReadonlyMap<string, Uint16Array> = buildMap()\n"
    )
    OUT_PATH.write_text(out.getvalue(), encoding="utf-8")
    print(f"glyphs={len(chars)} bytes={len(data)} -> {OUT_PATH} ({OUT_PATH.stat().st_size} bytes)")


if __name__ == "__main__":
    sys.exit(main())
